### ISSUE TITLE
CMS - testing HI runForest configs

### ISSUE THREAD

**Issue by katilp** [cernopendata/data-curation#175]
(see #174 for GTs)

Using configs from 
- https://github.com/CmsHI/cmssw/tree/forest_CMSSW_5_3_20/HeavyIonsAnalysis/JetAnalysis/test
- https://github.com/CmsHI/cmssw/blob/forest_CMSSW_7_5_8_patch3/HeavyIonsAnalysis/JetAnalysis/test/runForestAOD_pp_DATA_75X.py

(included in the container software)

##  Testing  configs

Testi input:

```
config_path: /code/CMSSW_5_3_20/src/HeavyIonsAnalysis/JetAnalysis/test/
container_image: gitlab-registry.cern.ch/cms-cloud/cmssw-docker-opendata/cmssw_5_3_20-slc6_amd64_gcc472:latest
job_inputs:
  - config: runForest_pPb_DATA_53X.py
    gt: GR_P_V43D
    inputfile: root://eospublic.cern.ch//eos/opendata/cms/hidata/HIRun2013/PAHighPt/RECO/PromptReco-v1/000/210/354/00000/6828E637-E262-E211-8478-BCAEC518FF7C.root
  - config: runForest_pPb_MC_53X.py
    gt: STARTHI53_V27
    inputfile: root://eospublic.cern.ch//eos/opendata/cms/himc/HiWinter13/Pyquen_Unquenched_AllQCDPhoton120_PhotonFilter35GeV_eta3_TuneZ2_pPb_5020GeV/GEN-SIM-RECO/pa_mixing_STARTHI53_V27-v1/00000/2AB91336-0042-E411-9D9B-24B6FDFF2B44.root
  - config: runForest_pp_DATA_53X.py
    gt: GR_P_V43D
    inputfile: root://eospublic.cern.ch//eos/opendata/cms/Run2013A/PPJet/RECO/PromptReco-v1/000/211/693/00000/E217D7AB-9775-E211-BCE7-003048F1110E.root 
  - config: runForest_pp_MC_53X.py
    gt: STARTHI53_V28
    inputfile: root://eospublic.cern.ch//eos/opendata/cms/himc/HiWinter13/Pythia_AllQCDPhotons_PtHat120_TuneZ2_cmssw53p14_2760GeV/GEN-SIM-RECO/STARTHI53_V28-v1/00000/0EAF7847-899B-E311-AC57-F04DA275BFFB.root
  - config: runForest_PbPb_MC_53X.py
    gt: STARTHI53_LV1
    inputfile: root://eospublic.cern.ch//eos/opendata/cms/himc/HiFall13DR53X/Hydjet1p8_TuneDrum_Quenched_MinBias_2760GeV/GEN-SIM-RECO/NoPileUp_STARTHI53_LV1-v1/00000/000D7E3C-BE6B-E411-A7D4-00266CF9B414.root
```

### runForest_pPb_MC_53X - STARTHI53_V27 ❌ -> ✅ ?

Fails with

```
 Beginning HLTBitAnalyzer Analysis
Initalizing HLTConfigProvider
Begin processing the 1st record. Run 1, Event 423361, LumiSection 1324 at 19-Jul-2023 11:11:48.262 CEST
----- Begin Fatal Exception 19-Jul-2023 11:12:00 CEST-----------------------
An exception of category 'ProductNotFound' occurred while
   [0] Processing run: 1 lumi: 1324 event: 423361
   [1] Running path 'ana_step'
   [2] Calling event method for module HackedTrackingParticleSelector/'cutsTPForFak'
Exception Message:
Principal::getByLabel: Found zero products matching all criteria
Looking for type: std::vector<TrackingParticle>
Looking for module label: mergedtruth
Looking for productInstanceName: MergedTrackTruth

   Additional Info:
      [a] If you wish to continue processing events after a ProductNotFound exception,
add "SkipEvent = cms.untracked.vstring('ProductNotFound')" to the "options" PSet in the configuration.

----- End Fatal Exception -------------------------------------------------
```

not clear where the process `cutsTPForFak` comes from (not defined in the config).
It and `cutsTPForEff` have been commented out in the pp config:

```
# grep cutsTPFor gt-test/*X.py
gt-test/runForest_PbPb_MC_53X.py:                            process.cutsTPForFak +
gt-test/runForest_PbPb_MC_53X.py:                            process.cutsTPForEff +
gt-test/runForest_pPb_MC_53X.py:                            process.cutsTPForFak +
gt-test/runForest_pPb_MC_53X.py:                            process.cutsTPForEff +
gt-test/runForest_pp_MC_53X.py:                            #process.cutsTPForFak +
gt-test/runForest_pp_MC_53X.py:                            #process.cutsTPForEff +
```

Commenting that, it fails with

```
----- Begin Fatal Exception 21-Jul-2023 12:22:16 CEST-----------------------
An exception of category 'ProductNotFound' occurred while
   [0] Processing run: 1 lumi: 1324 event: 423361
   [1] Running path 'ana_step'
   [2] Calling event method for module TrackAnalyzer/'ppTrack'
Exception Message:
Principal::getByLabel: Found zero products matching all criteria
Looking for type: std::vector<TrackingVertex>
Looking for module label: mergedtruth
Looking for productInstanceName: MergedTrackTruth

   Additional Info:
      [a] If you wish to continue processing events after a ProductNotFound exception,
add "SkipEvent = cms.untracked.vstring('ProductNotFound')" to the "options" PSet in the configuration.

----- End Fatal Exception -------------------------------------------------
```

NB that the PbPb_MC config has different tracks.

Before going further (and commenting out all tracks) see if changing the input to correspond to `Hijing` in

```
process.HeavyIonGlobalParameters = cms.PSet(
    centralityVariable = cms.string("HFtowersTrunc"),
    nonDefaultGlauberModel = cms.string("Hijing"),
    centralitySrc = cms.InputTag("pACentrality"),
    pPbRunFlip = cms.untracked.uint32(211313)
    )
```

Use `root://eospublic.cern.ch//eos/opendata/cms/himc/HiWinter13/Hijing_PPb502_MinimumBias/GEN-SIM-RECO/pa_STARTHI53_V27-v1/00000/0004C46B-FD9D-E311-BA57-848F69FD090E.root` instead 
But it is the same.

Note in `/runForest_pp_MC_53X.py`:
 `process.ppTrack.doSimTrack = cms.untracked.bool(False)`

Add this to runForest_pPb_MC_53X.py as (also commenting `cutsTPFor*`)

It runs without failure but not sure what is done with the tracks

###  runForest_PbPb_MC_53X - STARTHI53_LV1 ❌ -> ✅ ?

```
Begin processing the 2nd record. Run 1, Event 458338, LumiSection 57293 at 19-Jul-2023 11:37:23.708 CEST
OpenHLT analyser - missing collections:
        L1 jet objects: gctInternJetProducer:Internal:ANALYSIS
        GEN particles: genParticles::SIM
        RECO primary vertices, Offline0: offlinePrimaryVertices
----- Begin Fatal Exception 19-Jul-2023 11:41:16 CEST-----------------------
An exception of category 'CaloTowers' occurred while
   [0] Processing run: 1 lumi: 57293 event: 458338
   [1] Running path 'ana_step'
   [2] Calling event method for module PhotonProducer/'photons'
   [3] Using EventSetup component CaloTowerConstituentsMapBuilder/'' to make data CaloTowerConstituentsMap/'' in record IdealGeometryRecord
Exception Message:
Cell with id 3400723c is already mapped to a CaloTower Tower (18,3)
----- End Fatal Exception -------------------------------------------------
```

NB that the original test file probably included lower level content (filename `step3_RAW2DIGI_L1Reco_RECO_101_1_Uvh.root`) while the OD file in GEN-SIM-RECO

Commenting out `process.rechitAna` (with pfTowers) does not help.. 
Note that `process.rechitAna = cms.Sequence(process.rechitanalyzer+process.pfTowers)` is also under comment "To be cleaned" 

Commenting out `process.photonStep_withReco`  makes it run
Note that the others have `process.photonStep` (without Reco)

This looks, however, more like a Geometry problem but that's the same in all cases

```
# grep GeometryDB gt-test/*X.py
gt-test/runForest_PbPb_MC_53X.py:process.load('Configuration.Geometry.GeometryDB_cff')
gt-test/runForest_pPb_DATA_53X.py:process.load('Configuration.Geometry.GeometryDB_cff')
gt-test/runForest_pPb_MC_53X.py:process.load('Configuration.Geometry.GeometryDB_cff')
gt-test/runForest_pp_DATA_53X.py:process.load('Configuration.Geometry.GeometryDB_cff')
gt-test/runForest_pp_MC_53X.py:process.load('Configuration.Geometry.GeometryDB_cff')
```
Could also check what is in condition DB for the geometry (and what else....)

**Comment by katilp** [comment]
- [ ] Upload the test setup to an appropriate repository
- [ ] Check what in the configs makes  runForest_PbPb_MC_53X take substantially more time than the other
- [ ] Automate a control plot for the test runs

**Comment by katilp** [comment]
### runForest_pPb_DATA_53X - GR_P_V43D
![runForest_pPb_DATA_53X_h_npfpart](https://github.com/cernopendata/data-curation/assets/5859918/fff630bc-87c7-4e92-a9d8-6d1d11634575)
![runForest_pPb_DATA_53X_h_pfeta](https://github.com/cernopendata/data-curation/assets/5859918/c50e7d15-f76a-4f1d-b88c-b86d5a554549)

### runForest_pPb_MC_53X - STARTHI53_V27 
![runForest_pPb_MC_53X_h_npfpart](https://github.com/cernopendata/data-curation/assets/5859918/173b247c-982b-49cb-ba8a-0a38da6e42ae)
![runForest_pPb_MC_53X_h_pfeta](https://github.com/cernopendata/data-curation/assets/5859918/9642eb36-995f-4fcb-8b13-d19adb855371)

### runForest_pp_DATA_53X - GR_P_V43D
![runForest_pp_DATA_53X_h_npfpart](https://github.com/cernopendata/data-curation/assets/5859918/717127a8-0ca7-475f-bdec-ffaec23a802a)
![runForest_pp_DATA_53X_h_pfeta](https://github.com/cernopendata/data-curation/assets/5859918/a96f2ddc-004e-4238-ae63-b65144f60073)

### runForest_pp_MC_53X - STARTHI53_V28
![runForest_pp_MC_53X_h_npfpart](https://github.com/cernopendata/data-curation/assets/5859918/284b5dc3-bb4c-422d-81e1-1b1631ff0283)
![runForest_pp_MC_53X_h_pfeta](https://github.com/cernopendata/data-curation/assets/5859918/29effbbb-e8b6-412c-867a-d1e16ca63a15)

### runForest_PbPb_MC_53X - STARTHI53_LV1

![runForest_PbPb_MC_53X_h_npfpart](https://github.com/cernopendata/data-curation/assets/5859918/eb23c805-657e-49bb-924f-7c97eeae3c24)
![runForest_PbPb_MC_53X_h_pfeta](https://github.com/cernopendata/data-curation/assets/5859918/e9c1fd2c-73ff-4c86-9508-20a3101e2da4)

**Comment by katilp** [comment]
And the 2015 pp ref with

```
config_path: /code/CMSSW_7_5_8_patch3/src/HeavyIonsAnalysis/JetAnalysis/test/
container_image: gitlab-registry.cern.ch/cms-cloud/cmssw-docker-opendata/cmssw_7_5_8_patch3-slc6_amd64_gcc491:latest
job_inputs:
  - config: runForestAOD_pp_DATA_75X.py
    gt: 75X_dataRun2_v13
    inputfile: root://eospublic.cern.ch//eos/opendata/cms/Run2015E/HighPtJet80/AOD/PromptReco-v1/000/262/173/00000/3E8293B5-9894-E511-90E8-02163E011FA1.root
```


### runForestAOD_pp_DATA_75X - 75X_dataRun2_v13 ✅ 

![runForestAOD_pp_DATA_75X_h_npfpart](https://github.com/cernopendata/data-curation/assets/5859918/9990a41d-dd04-44af-b51e-6c1486c1fefd)

![runForestAOD_pp_DATA_75X_h_pfeta](https://github.com/cernopendata/data-curation/assets/5859918/fef975bb-1d2b-4e9d-b95a-def72726b438)
