### ISSUE TITLE
CMS - create a script for derived data records

### ISSUE THREAD

**Issue by katilp** [cernopendata/data-curation#212]
CMS 2016 release will include several "derived data" records structurally similar to e.g. https://opendata.cern.ch/record/12341
They will be:
- PF-enriched samples produced from the 2016 OD MiniAOD samples
- NanoAOD-type derivation from Run1 OD AOD samples

We should have a script template to create such records, that can be run in similar way as those for collision or MC records.

For the provenance, they will link to the parent dataset and the SW that was used to produce them (e.g. Run1 Nano: https://github.com/cernopendata/opendata.cern.ch/issues/3281). Both will be available as CODP records. So need for extended provenance listing as it is already available in the parent dataset record.

For the variable description, these records can link to listings of [this type](https://htmlpreview.github.io/?https://github.com/josephmoop/PFNano/blob/c6ea74b6f5ac6646c5ab86dac0b1a6e0fb4edeae/test/nanoAOD_2016MC.html).
This html files (one per type of production) should be hosted on the OD portal.

In the scripts, all metadata variables should be collected to the start of the script, for the ease of reuse.

**Comment by nancyhamdan** [comment]
Can refer to this [script](https://github.com/cernopendata/data-curation/blob/master/cms-2012-event-display-files/code/create-eventdisplay-files.py) from [cms-2012-event-display-files](https://github.com/cernopendata/data-curation/tree/master/cms-2012-event-display-files) as a starting point for new script for derived datasets, taking into account the following notes:

- Dataset listings for each type that will be used as input for the script can be found in eos `eos ls /eos/opendata/cms/derived-data/` e.g. `eos ls /eos/opendata/cms/derived-data/POET/23-Jul-22/`.  "merged" files should be excluded
- `authors` field will be set as "CMS Open Data Group" for all datasets
- `number_files` can be extracted from the derived-data directory in eos
- `methodology` corresponding to the "How were these data selected" section will differ from one type to another, can be changed in the Jinja html template with some conditional logic. File linked in this section will be a link to a corresponding software record
- Refer to [cernopendata/opendata.cern.ch/issues/3349](https://github.com/cernopendata/opendata.cern.ch/issues/3349) for `title` of each type of dataset
- Values for `description` under `abstract` can be extracted from a csv file that has datasets' descriptions. We could have a description template for each type of derived datasets
- `dataset_semantics` corresponding to the "Dataset characteristics" section can also be extracted as input from a csv file listing them for each dataset
- Instead of having to extract values for `description` and `dataset_semantics` from csv files, and to easily be able to configure the script with any other necessary hard coded values, we could have a yaml file that has these values and the script could take this file as input. The yaml file could have similar structure to this:
```
common values:
    collision_energy: "0.2TeV" 
    keywords:
        - education
        - outreach 
    description: >
        This is a very long description saying this and that. It can even have many lines. So it could be quite comfortable to 
        enter desired dataset descriptions even if they are really long.

dataset:
    name: "/BTag/Run2012C-22Jan2013-V1/AOD"
    number_of_events: 123456789
dataset:
    name: "/CTag/Run2012C-22Jan2013-V1/AOD"
    number_of_events: 456
dataset:
    name:" /DTag/Run2012C-22Jan2013-V1/AOD"
    number_of_events: 456324234
```
